### PR TITLE
adding the enforceHttps parameter to the avatar component

### PR DESCRIPTION
**Pull request by stetro**

### CODE REVIEW

**Comment by stetro** [comment]
refs #4

**Comment by snics** [comment]
@stetro wouldn't it be better if you could set the protocol dynamically? So more like that:
```
@Input('defaultProtocol') defaultProtocol = null;

const protocol = this.defaultProtocol ? defaultProtocol : '';
this.gravatarUrl = `${protocol}//www.gravatar.com/avatar/${hash}?s=${this.size}&d=404`;
```

**Comment by stetro** [comment]
ok, just updated it. Just thought about the usecase, if there is something other than http/s is needed. But I'm ok with that :)

**Comment by snics** [comment]
Yes, you're quite right, thank you :-)

**Pull request merged**
